### ISSUE TITLE
Decide on which extensions to include in 1.0

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticBundle#1]
Current list: https://github.com/SemanticMediaWiki/SemanticBundle/blob/master/composer.json#L23

**Comment by JeroenDeDauw** [comment]
@kghbln @mwjames @krabina which ones should still be added?

**Comment by JeroenDeDauw** [comment]
Some extensions with "semantic" in the name that are not included yet:

* Semantic Signup
* Semantic Forms Inputs
* Semantic Forms Select
* Semantic Graph
* Semantic Image Annotator
* Semantic Tasks
* Semantic Internal Objects - probably should not include as subobjects are there since forever
* Semantic Scribunto - only works with Scributo so not sure we should include this
* Semantic Interlanguage Links
* Semantic External Query Lookup
* Semantic Notifications - does this one have behavior enabled by default?

**Comment by krabina** [comment]
SIO is obsolete IMO. Many others are not actively developed and should therefore not be included, because you end up with a package causing trouble. 
The question is if we should also include some that have not Semantic in the name, but a) support Semantic features or b) are very relevant for any SMW installation.
e.g.
a) Title Icon, Comment Streams...
b) Page Forms, Variables, Chameleon, Replace Text, Mermaid...

**Comment by JeroenDeDauw** [comment]
I already included two extensions that can be used without SMW but provide SMW integration: Maps and Page Forms.

That said I do want to keep this package focused on SMW. So I do not want to include Variables and Replace Text. We can create another bundle, perhaps something like "enterprise bundle". The first thing that one would include would naturally be semantic bundle :)

@krabina can you explain why Title Icon and Comment Streams are semantic? (I do not know these extensions)

**Comment by kghbln** [comment]
> Semantic Interlanguage Links

:+1: 

> Mermaid

:+1: since it is needed for SRF "gantt", moreover "phpoffice/phpspreadsheet" for SRF "spreadsheet"

> Semantic Scribunto - only works with Scributo so not sure we should include this

This is a bit sad, but Scribunto needs extra effort, same with Semantic Approved Revs and Approves Revs. So, no we should not.

> Semantic External Query Lookup
Semantic Notifications - does this one have behavior enabled by default?

These two need a release and then they should be part of it. However these could be added at a later stage.

> Semantic Forms Select
> Semantic Tasks

I am afraid they should not make it.

We can indeed talk about Title Icon and Semantic Rating I guess. I have no experience with Comment Streams so I cannot tell how this on plays. Comment Streams is a bit like Maps, i.e. it works also without SMW. All the rest should imho not make it.

**Comment by krabina** [comment]
> @krabina can you explain why Title Icon and Comment Streams are semantic? (I do not know these extensions)

TitleIcon even requires SMW. You must set a property for the icon you are using.
CommentStreams can work without SMW, but when present, you can query for comments.

**Comment by JeroenDeDauw** [comment]
I've added Semantic Interlanguage Links and Mermaid.

> phpoffice/phpspreadsheet

Cannot include that since then we run into the same problem I had with SRF before: ext-gd.

> TitleIcon even requires SMW

I tried including that, but the combination of it not having a completed `composer.json` and the MediaWiki composer merge thing is making that impossible. For TitleIcon to be included the `composer.json` needs to be finished and the extension put on Packagist. Ping @cicalese

**Comment by kghbln** [comment]
> I've added Semantic Interlanguage Links and Mermaid.

Cool.

> Cannot include that since then we run into the same problem I had with SRF before: ext-gd.

Can this be fixed at SRF or is this a phpoffice thing?

> I tried including that, but the combination of it not having a completed composer.json and the MediaWiki composer merge thing is making that impossible.

Ouch, indeed forgot about this. I clone this one in. Same for Semantic Rating I believe. Another positive side effect will be that I can then generate code documentation on doc.s-mw.o for these, too.

**Comment by JeroenDeDauw** [comment]
> Can this be fixed at SRF or is this a phpoffice thing?

phpoffice

**Comment by kghbln** [comment]
> phpoffice

end of that story. No worries.

**Comment by JeroenDeDauw** [comment]
Closing this now since 1.0 has been released. Feel free to open new issues as you see fit.

**Comment by cicalese** [comment]
> > TitleIcon even requires SMW
> 
> I tried including that, but the combination of it not having a completed `composer.json` and the MediaWiki composer merge thing is making that impossible. For TitleIcon to be included the `composer.json` needs to be finished and the extension put on Packagist. Ping @cicalese

I'll work on that for a future release.

DisplayTitle is another extension that could eventually be included. While it does not use SMW, it complements the features in SMW related to display titles.
